@startuml
skinparam componentStyle uml2

title Component Diagram

node gstcam {
    [Camera] as cam
    [Computer] as com
    [Screen] as scr
}

cam -r-> com: USB or\ninternal bus
com -r-> scr: VGA, DVI, HDMI\nor DisplayPort

@enduml
